# Generated by Django 3.1.1 on 2023-05-27 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230527_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_twitter',
        ),
    ]
